version: '3.8'

services:
  app:
    image: ngntu10/optimart-api:v4.0
    container_name: spring-app
    ports:
      - "8085:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/optimart
      DB_USERNAME: ngntu10
      DB_PASSWORD: nguyentu1005
    depends_on:
      - db
    networks:
      - optimart-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: optimart
      POSTGRES_USER: ngntu10
      POSTGRES_PASSWORD: nguyentu1005
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - optimart-network
volumes:
  postgres-data: {}

networks:
  optimart-network:
    driver: bridge
